# Generated by Django 4.1.7 on 2023-03-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='content',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
