# Generated by Django 4.1.7 on 2023-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='', max_length=10),
        ),
    ]
