# Generated by Django 4.1.7 on 2023-03-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('passowrd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('object_id', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrequest',
            name='actor',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrequest',
            name='object',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='author_id',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='items',
            field=models.ManyToManyField(to='main.object'),
        ),
    ]
