# Generated by Django 4.1.7 on 2023-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_node_object_comment_author_followrequest_actor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='passowrd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.TextField(default='text/markdown', max_length=255),
        ),
    ]
