# Generated by Django 4.1.7 on 2023-03-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_post_id_alter_profile_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='content',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='inbox',
            name='FollowRequest',
            field=models.ManyToManyField(blank=True, related_name='inbox', to='main.followrequest'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='inbox', to='main.post'),
        ),
    ]
