# Generated by Django 4.1.6 on 2023-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_followers_author_following_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='identifier',
            field=models.CharField(default=None, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
