# Generated by Django 4.1.6 on 2023-02-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_author_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='following',
        ),
    ]
