# Generated by Django 4.1.7 on 2023-03-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_inbox_content_remove_inbox_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='FollowRequest',
            new_name='followRequests',
        ),
    ]
