# Generated by Django 4.1.7 on 2023-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_post_type_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inbox',
            field=models.ManyToManyField(to='main.object'),
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
