# Generated by Django 4.1.7 on 2023-03-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_id_alter_commentlike_id_alter_inbox_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
