# Generated by Django 4.1.7 on 2023-03-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_markdown_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
