# Generated by Django 4.1.7 on 2023-03-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
