# Generated by Django 4.1.7 on 2023-03-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(default='https://github.com/Gerrinator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='host',
            field=models.URLField(default='http://localhost:8000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
