# Generated by Django 4.1.7 on 2023-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comment_post_comment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
