# Generated by Django 4.1.7 on 2023-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_displayname_profile_github_profile_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_follower', to='main.profile'),
        ),
    ]
