# Generated by Django 4.1.7 on 2023-03-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_post_author_id_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author_id',
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
            preserve_default=False,
        ),
    ]
