# Generated by Django 4.1.7 on 2023-03-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_post_id_alter_post_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
