# Generated by Django 4.1.7 on 2023-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_like_author_id_like_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(related_name='friend_profiles', to='main.follower'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follower_list',
            field=models.ManyToManyField(related_name='following_profiles', to='main.follower'),
        ),
    ]
