# Generated by Django 4.1.7 on 2023-03-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
    ]
