# Generated by Django 4.1.7 on 2023-03-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_pub_date'),
        ('main', '0010_alter_profile_followers'),
    ]

    operations = [
    ]
