# Generated by Django 4.1.7 on 2023-03-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_text_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text_post',
        ),
    ]
