# Generated by Django 4.1.7 on 2023-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_comment_post_id_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
    ]
