# Generated by Django 4.1.7 on 2023-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_author_comment_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
