# Generated by Django 4.1.7 on 2023-03-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_post_visibility_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.IntegerField(default=0),
        ),
    ]
