# Generated by Django 4.1.7 on 2023-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_post_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(default=0),
        ),
    ]
